stages:
  - test

test_stage:
  environment:
    name: production
    url: https://lisiewiczdesign.com
  allow_failure: true
  stage: test
  script:
    - echo "Project environment ${CI_ENVIRONMENT_NAME}"
    - echo "Project url ${CI_ENVIRONMENT_URL}"
    - echo "Pipeline project url ${CI_PIPELINE_URL}"
  tags:
    - lisiewiczdesign
