version: "3.3"

services:
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  # backend:
  #   container_name: backend
  #   environment:
  #     - MONGO_HOST=mongo
  #     - MONGO_PORT=27017
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  frontend:
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    build:
      context: .
      dockerfile: ./frontend/dev.Dockerfile
    ports:
      - "3000:3000"
